version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '4000:4000'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "3002:3002"
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/twitter
    depends_on:
      - db
volumes:
  bundle:
  mysql_data:
